// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKFHZvTA0VkmnCOVreAFtNeXsdBnIWbo8',
    appId: '1:682406191202:web:449103995dd8f14a1ab13b',
    messagingSenderId: '682406191202',
    projectId: 'cloudmessage-e53aa',
    authDomain: 'cloudmessage-e53aa.firebaseapp.com',
    storageBucket: 'cloudmessage-e53aa.firebasestorage.app',
    measurementId: 'G-EVG4C7CZQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsxBM253JzfSbyyS70UsK8e3eeD73dP8A',
    appId: '1:682406191202:android:459e5e37f610de4a1ab13b',
    messagingSenderId: '682406191202',
    projectId: 'cloudmessage-e53aa',
    storageBucket: 'cloudmessage-e53aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDByVbYbJqwR80ILs8Q0qDwlyRVQAkhXSo',
    appId: '1:682406191202:ios:c5c44382bbc933401ab13b',
    messagingSenderId: '682406191202',
    projectId: 'cloudmessage-e53aa',
    storageBucket: 'cloudmessage-e53aa.firebasestorage.app',
    iosBundleId: 'com.example.ca14CloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDByVbYbJqwR80ILs8Q0qDwlyRVQAkhXSo',
    appId: '1:682406191202:ios:c5c44382bbc933401ab13b',
    messagingSenderId: '682406191202',
    projectId: 'cloudmessage-e53aa',
    storageBucket: 'cloudmessage-e53aa.firebasestorage.app',
    iosBundleId: 'com.example.ca14CloudMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKFHZvTA0VkmnCOVreAFtNeXsdBnIWbo8',
    appId: '1:682406191202:web:6521355781416ce41ab13b',
    messagingSenderId: '682406191202',
    projectId: 'cloudmessage-e53aa',
    authDomain: 'cloudmessage-e53aa.firebaseapp.com',
    storageBucket: 'cloudmessage-e53aa.firebasestorage.app',
    measurementId: 'G-BR0D0H8S69',
  );
}
